"""add lossless_mode to user_settings

Revision ID: 1a6bb4012e25
Revises: f562e1e476c2
Create Date: 2026-01-18 16:25:55.769479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6bb4012e25'
down_revision: Union[str, Sequence[str], None] = 'f562e1e476c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('lossless_mode', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'lossless_mode')
    # ### end Alembic commands ###
