"""remove UserSettings and ChatSettings

Revision ID: 4b154c4760db
Revises: 1a6bb4012e25
Create Date: 2026-02-25 09:45:17.819967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b154c4760db'
down_revision: Union[str, Sequence[str], None] = '1a6bb4012e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('chat_settings')
    op.add_column('chats', sa.Column('settings_json', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('users', sa.Column('settings_json', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings_json')
    op.drop_column('chats', 'settings_json')
    op.create_table('chat_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.VARCHAR(length=2), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.Column('send_notifications', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('send_raw', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('send_music_covers', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('send_reactions', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('ping_reaction', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('auto_caption', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('auto_translate_titles', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('title_language', sa.VARCHAR(length=2), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.Column('preferred_services', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('blocked_services', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('allow_playlists', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('chat_settings_chat_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_settings_pkey')),
    sa.UniqueConstraint('chat_id', name=op.f('chat_settings_chat_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.VARCHAR(length=2), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.Column('send_notifications', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('send_raw', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('send_music_covers', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('send_reactions', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('ping_reaction', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('auto_caption', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('auto_translate_titles', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('title_language', sa.VARCHAR(length=2), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.Column('lossless_mode', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_settings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_settings_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_settings_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
