"""add cache_key

Revision ID: a8311dee8ec2
Revises: 4b154c4760db
Create Date: 2026-04-24 13:10:27.180893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8311dee8ec2'
down_revision: Union[str, Sequence[str], None] = '4b154c4760db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'mediacache' not in tables:
        op.create_table('mediacache',
        sa.Column('media_id', sa.Integer(), nullable=False),
        sa.Column('cache_key', sa.String(), nullable=False),
        sa.Column('telegram_file_id', sa.String(), nullable=True),
        sa.Column('telegram_document_file_id', sa.String(), nullable=True),
        sa.Column('media_type', sa.String(), nullable=False),
        sa.Column('platform', sa.String(), nullable=False),
        sa.Column('data', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('media_id'),
        sa.UniqueConstraint('cache_key')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'mediacache' in tables:
        op.drop_table('mediacache')
    # ### end Alembic commands ###
